// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kkd16/parry/internal/notify (interfaces: Provider,Confirmer)
//
// Generated by this command:
//
//	mockgen -destination=mocks/provider.go -package=mocks github.com/kkd16/parry/internal/notify Provider,Confirmer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	notify "github.com/kkd16/parry/internal/notify"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockProvider) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockProviderMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockProvider)(nil).Name))
}

// NewConfirmer mocks base method.
func (m *MockProvider) NewConfirmer(cfg map[string]any) (notify.Confirmer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewConfirmer", cfg)
	ret0, _ := ret[0].(notify.Confirmer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewConfirmer indicates an expected call of NewConfirmer.
func (mr *MockProviderMockRecorder) NewConfirmer(cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewConfirmer", reflect.TypeOf((*MockProvider)(nil).NewConfirmer), cfg)
}

// RunSetup mocks base method.
func (m *MockProvider) RunSetup(policyPath string) (notify.SetupResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunSetup", policyPath)
	ret0, _ := ret[0].(notify.SetupResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunSetup indicates an expected call of RunSetup.
func (mr *MockProviderMockRecorder) RunSetup(policyPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunSetup", reflect.TypeOf((*MockProvider)(nil).RunSetup), policyPath)
}

// SendTest mocks base method.
func (m *MockProvider) SendTest(ctx context.Context, cfg map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTest", ctx, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendTest indicates an expected call of SendTest.
func (mr *MockProviderMockRecorder) SendTest(ctx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTest", reflect.TypeOf((*MockProvider)(nil).SendTest), ctx, cfg)
}

// MockConfirmer is a mock of Confirmer interface.
type MockConfirmer struct {
	ctrl     *gomock.Controller
	recorder *MockConfirmerMockRecorder
	isgomock struct{}
}

// MockConfirmerMockRecorder is the mock recorder for MockConfirmer.
type MockConfirmerMockRecorder struct {
	mock *MockConfirmer
}

// NewMockConfirmer creates a new mock instance.
func NewMockConfirmer(ctrl *gomock.Controller) *MockConfirmer {
	mock := &MockConfirmer{ctrl: ctrl}
	mock.recorder = &MockConfirmerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfirmer) EXPECT() *MockConfirmerMockRecorder {
	return m.recorder
}

// Confirm mocks base method.
func (m *MockConfirmer) Confirm(ctx context.Context, req notify.ConfirmRequest) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Confirm", ctx, req)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Confirm indicates an expected call of Confirm.
func (mr *MockConfirmerMockRecorder) Confirm(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Confirm", reflect.TypeOf((*MockConfirmer)(nil).Confirm), ctx, req)
}
