version: 2

updates:
  # Go modules
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    groups:
      minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
