// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kkd16/parry/internal/check (interfaces: Agent)
//
// Generated by this command:
//
//	mockgen -destination=mocks/agent.go -package=mocks github.com/kkd16/parry/internal/check Agent
//

// Package mocks is a generated GoMock package.
package mocks

import (
	io "io"
	reflect "reflect"

	check "github.com/kkd16/parry/internal/check"
	gomock "go.uber.org/mock/gomock"
)

// MockAgent is a mock of Agent interface.
type MockAgent struct {
	ctrl     *gomock.Controller
	recorder *MockAgentMockRecorder
	isgomock struct{}
}

// MockAgentMockRecorder is the mock recorder for MockAgent.
type MockAgentMockRecorder struct {
	mock *MockAgent
}

// NewMockAgent creates a new mock instance.
func NewMockAgent(ctrl *gomock.Controller) *MockAgent {
	mock := &MockAgent{ctrl: ctrl}
	mock.recorder = &MockAgentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgent) EXPECT() *MockAgentMockRecorder {
	return m.recorder
}

// Detect mocks base method.
func (m *MockAgent) Detect(raw map[string]any) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detect", raw)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Detect indicates an expected call of Detect.
func (mr *MockAgentMockRecorder) Detect(raw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detect", reflect.TypeOf((*MockAgent)(nil).Detect), raw)
}

// Name mocks base method.
func (m *MockAgent) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockAgentMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockAgent)(nil).Name))
}

// Parse mocks base method.
func (m *MockAgent) Parse(raw map[string]any) (*check.ToolCall, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", raw)
	ret0, _ := ret[0].(*check.ToolCall)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockAgentMockRecorder) Parse(raw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockAgent)(nil).Parse), raw)
}

// Respond mocks base method.
func (m *MockAgent) Respond(w io.Writer, result check.Result) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Respond", w, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// Respond indicates an expected call of Respond.
func (mr *MockAgentMockRecorder) Respond(w, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Respond", reflect.TypeOf((*MockAgent)(nil).Respond), w, result)
}
